name: DB Workflow

on:
  schedule:
    - cron: "0 * * * *"     # Jede volle Stunde
    - cron: "5 0 * * *"     # Täglich um 00:05
  workflow_dispatch:

permissions:
  contents: write   # Erlaubt das Schreiben ins Repository

jobs:
  fetch_hourly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set environment variables from Secrets
        run: |
          echo "DB_CLIENT_ID=${{ secrets.DB_CLIENT_ID }}" >> .env
          echo "DB_API_KEY=${{ secrets.DB_API_KEY }}" >> .env

      - name: Fetch Data Hourly
        run: poetry run python src/01_fetch_data.py

      # Dateien commiten (z. B. stündliche CSVs in 01_data/01_raw/API)
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes (Hourly Data)
        run: |
          git add 01_data/01_raw/API/*.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add hourly data files [skip ci]"
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  daily_combine_and_clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set environment variables from Secrets
        run: |
          echo "DB_CLIENT_ID=${{ secrets.DB_CLIENT_ID }}" >> .env
          echo "DB_API_KEY=${{ secrets.DB_API_KEY }}" >> .env

      - name: Combine Daily Data
        run: poetry run python src/03_combine_daily.py

      - name: Determine yesterday's date
        run: echo "DATE=$(date -d 'yesterday' '+%y%m%d')" >> $GITHUB_ENV

      - name: Clean Data
        run: poetry run python src/02_clean_data.py ${{ env.DATE }}

      - name: Append to combined
        run: poetry run python src/04_append_to_combined.py ${{ env.DATE }}

      # Änderungen nach täglichem Combine & Clean committen
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes (Daily and Combined Data)
        run: |
          # Hier z. B. tagesweise kombinierte Dateien
          git add 01_data/02_intermediate/*.csv
          # Und ggf. die aktualisierte combined.csv
          git add 01_data/03_processed/combined.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Daily combined and cleaned data [skip ci]"
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}