name: DB Workflow

on:
  # Wird jede Stunde ausgeführt
  schedule:
    - cron: "0 * * * *"
    # Wird täglich um 00:05 ausgeführt
    - cron: "5 0 * * *" 
  # Ermöglicht manuelles Ausführen via GitHub Actions UI
  workflow_dispatch:

jobs:
  fetch_hourly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Python 3.11 Setup
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install

      # Secrets in .env-Datei schreiben
      - name: Set environment variables
        run: |
          echo "DB_CLIENT_ID=${{ secrets.DB_CLIENT_ID }}" >> .env
          echo "DB_API_KEY=${{ secrets.DB_API_KEY }}" >> .env

      - name: Fetch Data Hourly
        run: poetry run python src/01_fetch_data.py

  daily_combine_and_clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Python 3.11 Setup
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install

      # Secrets in .env-Datei schreiben
      - name: Set environment variables
        run: |
          echo "DB_CLIENT_ID=${{ secrets.DB_CLIENT_ID }}" >> .env
          echo "DB_API_KEY=${{ secrets.DB_API_KEY }}" >> .env

      # Tagesweise Kombination
      - name: Combine Daily Data
        run: poetry run python src/03_combine_daily.py
      
      # Gestern's Datum ermitteln
      - name: Determine yesterday's date
        run: echo "DATE=$(date -d 'yesterday' '+%y%m%d')" >> $GITHUB_ENV
      
      # Bereinigen der Daten von gestern
      - name: Clean Data
        run: poetry run python src/02_clean_data.py ${{ env.DATE }}
      
      # Anfügen an combined.csv
      - name: Append to combined
        run: poetry run python src/04_append_to_combined.py ${{ env.DATE }}