name: DB Workflow

on:
  schedule:
    - cron: "0 * * * *"     # Jede Stunde Daten abrufen
    - cron: "5 0 * * *"     # Täglich um 00:05 tagesweise kombinieren, bereinigen und anhängen
  workflow_dispatch:

jobs:
  fetch_hourly:
    if: "github.event_name == 'schedule'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Fetch Data Hourly
        run: poetry run python src/01_fetch_data.py

  daily_combine_and_clean:
    if: "github.event_name == 'schedule'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Combine Daily Data
        run: poetry run python src/03_combine_daily.py
      - name: Determine yesterday's date
        run: echo "DATE=$(date -d 'yesterday' '+%y%m%d')" >> $GITHUB_ENV
      - name: Clean Data
        run: poetry run python src/02_clean_data.py $DATE
      - name: Append to combined
        run: poetry run python src/04_append_to_combined.py $DATE
